### ISSUE TITLE
Finish adding all past CCC problems

### ISSUE THREAD

**Issue by quantum5** [DMOJ/problems#9]
Some old problem statement are borrowed with defects from wcipeg and should probably be replaced as well.

**Comment by FatalEagle** [comment]
To this end, we can allow normal users to submit problems (even if they're not problemsetters) and gain contribution. Admin or other problemsetters can approve problems.

**Comment by 067953240** [comment]
If I can help, let me know.

-Max

**Comment by BinAccel** [comment]
@quantum5 This can be closed now?
